PowerData = read.table("household_power_consumption.txt", header = TRUE, sep = ';', na.strings = "?",stringsAsFactors = FALSE)
PowerData$Date <- as.Date(PowerData$Date, format="%d/%m/%Y")
ImportantDates <- PowerData[(PowerData$Date=="2007-02-01") | (PowerData$Date=="2007-02-02"),]
ImportantDates$CombinedDT = as.POSIXct(paste(ImportantDates$Date, ImportantDates$Time), format="%Y-%m-%d %H:%M:%S")
par(mfcol=c(2,2))
plot(ImportantDates$CombinedDT,ImportantDates$Global_active_power,type = "l",ylab = "Global Active Power",xlab = "")
plot(ImportantDates$CombinedDT,ImportantDates$Sub_metering_1, type = "l",ylab = "Energy sub metering",xlab = "")
lines(ImportantDates$CombinedDT,ImportantDates$Sub_metering_2, col="red",type = "l")
lines(ImportantDates$CombinedDT,ImportantDates$Sub_metering_3, col="blue",type = "l")
legend("topright",col=c("black", "red", "blue"),c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty=1)
plot(ImportantDates$CombinedDT,ImportantDates$Voltage, type = "l",xlab = "datetime", ylab = "Voltage")
plot(ImportantDates$CombinedDT,ImportantDates$Global_reactive_power, type = "l",xlab = "datetime", ylab = "Global_reactive_power")
dev.copy(png, file = "plot4.png", height = 480, width = 480)
dev.off()
